#!/usr/bin/env bash
# fix-node-shebang.sh — Replace a globally-installed node tool's bin symlink
# with a bash wrapper that runs it under bun instead of node.
#
# WHY: Termux's node (bionic-linked) reports process.platform === "android",
# which many packages reject (playwright, rollup, lightningcss, etc.).
# Bun (via glibc-runner) reports "linux" and can load glibc native binaries.
#
# USAGE:
#   fix-node-shebang.sh <command>            # fix a single command
#   fix-node-shebang.sh --list               # show fixable commands
#   fix-node-shebang.sh --restore <command>  # undo (re-symlink from global install)
#
# EXAMPLES:
#   fix-node-shebang.sh mcp-server-playwright
#   fix-node-shebang.sh astro
#   fix-node-shebang.sh --list

set -euo pipefail

BUN_BIN="${HOME}/.bun/bin"
GLOBAL_MODULES="${HOME}/.bun/install/global/node_modules"

usage() {
  echo "Usage: fix-node-shebang.sh [--list | --restore <cmd> | <cmd>]"
  exit 1
}

# List all bun global bin entries that are symlinks to #!/usr/bin/env node scripts
list_fixable() {
  echo "Fixable commands in ${BUN_BIN}:"
  local found=0
  for f in "${BUN_BIN}"/*; do
    [ -f "$f" ] || continue
    local name
    name=$(basename "$f")
    # Skip bun itself and known non-node binaries
    [[ "$name" == bun* ]] && continue

    # Check if it's a symlink to a node script
    if [ -L "$f" ]; then
      local target
      target=$(readlink -f "$f")
      if head -1 "$target" 2>/dev/null | grep -q '#!/usr/bin/env node'; then
        echo "  ${name}  →  $(readlink "$f")  [symlink, fixable]"
        found=1
      fi
    # Check if it's already wrapped
    elif head -1 "$f" 2>/dev/null | grep -q '#!/usr/bin/env bash'; then
      if grep -q 'exec bun' "$f" 2>/dev/null; then
        echo "  ${name}  [already wrapped]"
        found=1
      fi
    fi
  done
  [ $found -eq 0 ] && echo "  (none found)"
  return 0
}

# Resolve the original JS entry point from a symlink or wrapper
resolve_target() {
  local cmd="$1"
  local bin="${BUN_BIN}/${cmd}"

  if [ -L "$bin" ]; then
    # It's still a symlink — resolve it
    readlink -f "$bin"
  elif [ -f "$bin" ] && grep -q 'exec bun' "$bin" 2>/dev/null; then
    # Already wrapped — extract the target path from the wrapper
    grep 'exec bun' "$bin" | sed 's/exec bun "\{0,1\}//' | sed 's/"\{0,1\} "\$@"//'
  else
    echo "Error: ${bin} is not a symlink or bun wrapper" >&2
    exit 1
  fi
}

# Create the bun wrapper
wrap_command() {
  local cmd="$1"
  local bin="${BUN_BIN}/${cmd}"

  if [ ! -e "$bin" ]; then
    echo "Error: ${bin} does not exist" >&2
    exit 1
  fi

  # Already wrapped?
  if [ -f "$bin" ] && ! [ -L "$bin" ] && grep -q 'exec bun' "$bin" 2>/dev/null; then
    echo "${cmd} is already wrapped"
    return 0
  fi

  local target
  target=$(readlink -f "$bin")

  if ! head -1 "$target" 2>/dev/null | grep -q '#!/usr/bin/env node'; then
    echo "Error: ${target} does not have a #!/usr/bin/env node shebang" >&2
    exit 1
  fi

  # Replace symlink with wrapper
  rm "$bin"
  cat > "$bin" <<WRAPPER
#!/usr/bin/env bash
# Auto-generated by fix-node-shebang.sh — runs under bun instead of node
# so process.platform === "linux" (not "android") on Termux.
# Original target: ${target}
exec bun "${target}" "\$@"
WRAPPER
  chmod +x "$bin"
  echo "Wrapped: ${cmd} → bun ${target}"
}

# Restore original symlink
restore_command() {
  local cmd="$1"
  local bin="${BUN_BIN}/${cmd}"

  if [ -L "$bin" ]; then
    echo "${cmd} is already a symlink, nothing to restore"
    return 0
  fi

  if [ ! -f "$bin" ]; then
    echo "Error: ${bin} does not exist" >&2
    exit 1
  fi

  local target
  target=$(grep 'exec bun' "$bin" | sed 's/exec bun "\{0,1\}//' | sed 's/"\{0,1\} "\$@"//')

  if [ -z "$target" ] || [ ! -f "$target" ]; then
    echo "Error: could not determine original target from wrapper" >&2
    exit 1
  fi

  rm "$bin"
  ln -s "$target" "$bin"
  echo "Restored: ${cmd} → ${target}"
}

# --- Main ---
[ $# -lt 1 ] && usage

case "$1" in
  --list)    list_fixable ;;
  --restore) [ $# -lt 2 ] && usage; restore_command "$2" ;;
  --help|-h) usage ;;
  *)         wrap_command "$1" ;;
esac
